=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/attendenceValidation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

     <!-- ========================================================================================= -->
    <!-- Type -->
    <xs:simpleType name="id">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:enumeration value="absent"/>
            <xs:enumeration value="present"/>
        </xs:restriction>
    </xs:simpleType>
        <!-- ========================================================================================= -->
        
        
     <!-- ========================================================================================= -->
    <!-- elements -->
				<xs:element name="id" type="id"/>
                <xs:element name="stdId" type="id"/>
                <xs:element name="date" type="xs:date"/>
                <xs:element name="status" type="status"/>
      <!-- ========================================================================================= -->
     
      
       <!-- ========================================================================================= -->
    <!-- group -->
      	<xs:group name="recourdElement">
		<xs:sequence>
			<xs:element ref="id"/>
			<xs:element ref="stdId"/>
			<xs:element ref="date"/>
			<xs:element ref="status"/>
		</xs:sequence>
	</xs:group>
	<!-- ========================================================================================= -->
	
	
	<xs:element name="attendanceRecord">
        <xs:complexType>
            <xs:sequence>  
                <xs:group ref="recourdElement"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attendanceRecords">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="attendanceRecord" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
       

</xs:schema>

=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/attendence.xml
<attendanceRecords xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="./attendenceValidation.xsd">
    <attendanceRecord>
        <id>1</id>
        <stdId>101</stdId>
        <date>2024-02-17</date>
        <status>present</status>
        <classId>1</classId>
    </attendanceRecord>
    
    <attendanceRecord>
        <id>2</id>
        <stdId>102</stdId>
        <date>2024-02-17</date>
        <status>absent</status>
        <classId>1</classId>

    </attendanceRecord>
    
    <attendanceRecord>
        <id>3</id>
        <stdId>103</stdId>
        <date>2024-02-18</date>
        <status>present</status>
        <classId>1</classId>

    </attendanceRecord>
    <attendanceRecord>
        <id>4</id>
        <stdId>101</stdId>
        <date>2024-02-18</date>
        <status>present</status>
        <classId>1</classId>
    </attendanceRecord>
    
    <attendanceRecord>
        <id>5</id>
        <stdId>102</stdId>
        <date>2024-02-18</date>
        <status>absent</status>
        <classId>1</classId>
    </attendanceRecord>
    
    <attendanceRecord>
        <id>6</id>
        <stdId>103</stdId>
        <date>2024-02-18</date>
        <status>present</status>
        <classId>1</classId>
    </attendanceRecord>
</attendanceRecords>
