=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/classValidation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <!-- Define simple types -->
    <xs:simpleType name="idType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <!-- Add a pattern to enforce class name format, for example, starting with a letter (A, B, C) followed by a digit (1, 2, 3) -->
            <xs:pattern value="[A-C][1-3]"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- elements -->
    <xs:element name="id" type="idType"/>
    <xs:element name="teacherId" type="idType"/>
    <xs:element name="name" type="nameType"/>

    <!--stdClass -->
    <xs:element name="stdClass">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="teacherId"/>
                <xs:element ref="name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Root element -->
    <xs:element name="classes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="stdClass" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/classes.xml
<?xml version="1.0" encoding="utf-8"?>
<classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./classValidation.xsd">
  <stdClass>
    <id>4</id>
    <name>html</name>
    <teacherId>3</teacherId>
  </stdClass>
  <stdClass>
    <id>5</id>
    <name>ooo</name>
    <teacherId>3</teacherId>
  </stdClass>
  <stdClass>
    <id>6</id>
    <name>kkk</name>
    <teacherId>3</teacherId>
  </stdClass>
  <stdClass>
    <id>7</id>
    <name>iiiikjh</name>
    <teacherId>3</teacherId>
  </stdClass>
  <stdClass>
    <id>8</id>
    <name>bbjk</name>
    <teacherId>4</teacherId>
  </stdClass>
  <stdClass>
    <id>9</id>
    <name>htii</name>
    <teacherId>3</teacherId>
  </stdClass>
  <stdClass>
    <id>10</id>
    <name>html</name>
    <teacherId>14</teacherId>
  </stdClass>
  <stdClass>
    <id>11</id>
    <name>js</name>
    <teacherId>15</teacherId>
  </stdClass>
</classes>
