=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/userValidate.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="userName" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="role" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AbdelRahman-Ahmed1212/DotnetXMLproject/Data/users.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="userValidate.xsd">
<user>
    <id>1</id>
    <name>John Doe</name>
    <userName>john_doe</userName>
    <password>john123</password>
    <role>Admin</role>
</user>
<user>
    <id>2</id>
    <name>Alice Smith</name>
    <userName>alice_smith</userName>
    <password>alice456</password>
    <role>Teacher</role>
</user>
<user>
    <id>3</id>
    <name>Bob Johnson</name>
    <userName>bob_johnson</userName>
    <password>bob789</password>
    <role>Student</role>
</user>


</Users>
